/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package olc1.proyecto.ui;
import olc1.proyecto.analizadores.Lexer;
import olc1.proyecto.analizadores.Parser;
import java.io.StringReader;
import olc1.proyecto.ui.Consola;
import java.util.List;
import olc1.proyecto.ast.Instruccion;
import java.awt.Desktop;
import java.io.File;
import java.net.URI;





/**
 *
 * @author USUARIO
 */
public class FrmPrincipal extends javax.swing.JFrame {
    private java.util.Map<java.awt.Component, java.io.File> archivosPorTab = new java.util.HashMap<>();
    private olc1.proyecto.interprete.Entorno envEjecucion;
    private java.io.File ultimoReporteTS;
    private java.io.File ultimoReporteErrores;
    private java.io.File ultimoReporteAST;
 
    /**
     * Creates new form FrmPrincipal
     */
    public FrmPrincipal() {
        initComponents();
        Consola.setArea(Txtconsola);
        setLocationRelativeTo(null); // centrar
        
        crearNuevaPestania("Sin título 1", "");
        limpiarConsola();
    }
        private void crearNuevaPestania(String titulo, String contenido) {
        javax.swing.JTextArea editor = new javax.swing.JTextArea();
        editor.setText(contenido);
        editor.setLineWrap(true);
        editor.setWrapStyleWord(true);

        javax.swing.JScrollPane scroll = new javax.swing.JScrollPane(editor);

        tabEditor.addTab(titulo, scroll);
        tabEditor.setSelectedComponent(scroll);

        // Al inicio no tiene archivo asociado
        archivosPorTab.put(scroll, null);
    }
            private javax.swing.JTextArea getEditorActual() {
        java.awt.Component comp = tabEditor.getSelectedComponent();
        if (comp instanceof javax.swing.JScrollPane scroll) {
            java.awt.Component view = scroll.getViewport().getView();
            if (view instanceof javax.swing.JTextArea area) {
                return area;
            }
        }
        return null;
    }

    private String getTextoEditorActual() {
        javax.swing.JTextArea editor = getEditorActual();
        return (editor != null) ? editor.getText() : "";
    }

    private void setTextoEditorActual(String texto) {
        javax.swing.JTextArea editor = getEditorActual();
        if (editor != null) {
            editor.setText(texto);
        }
    }
    
    public void limpiarConsola() {
        Txtconsola.setText("");
    }

    public void escribirConsola(String texto) {
        Txtconsola.append(texto);
    }

    public void escribirConsolaLinea(String texto) {
        Txtconsola.append(texto + "\n");
    }
    
    public interface Instruccion {
    void ejecutar();  // Método para ejecutar la instrucción
}

    private void abrirArchivoEnNavegador(String ruta) {
    try {
        File f = new File(ruta);
        if (!f.exists()) {
            Consola.escribirLinea("No existe el archivo: " + f.getAbsolutePath());
            return;
        }

        if (!Desktop.isDesktopSupported()) {
            Consola.escribirLinea("Desktop no soportado en este sistema.");
            return;
        }

        Desktop.getDesktop().browse(f.toURI());
    } catch (Exception ex) {
        Consola.escribirLinea("No se pudo abrir el reporte: " + ex.getMessage());
    }
}


public interface Expresion {
    Object evaluar();  // Método para evaluar la expresión
}






    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        tabEditor = new javax.swing.JTabbedPane();
        panelConsola = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Txtconsola = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        Archivo = new javax.swing.JMenu();
        itemNuevo = new javax.swing.JMenuItem();
        itemAbrir = new javax.swing.JMenuItem();
        itemGuardar = new javax.swing.JMenuItem();
        itemGuardarComo = new javax.swing.JMenuItem();
        itemSalir = new javax.swing.JMenuItem();
        MenuEjecutar = new javax.swing.JMenu();
        Ejecutar = new javax.swing.JMenuItem();
        menuReportes = new javax.swing.JMenu();
        itemTablaSimbolos = new javax.swing.JMenuItem();
        itemErrores = new javax.swing.JMenuItem();
        menuASTAction = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("JavaUsac 201801391");

        Txtconsola.setEditable(false);
        Txtconsola.setColumns(20);
        Txtconsola.setLineWrap(true);
        Txtconsola.setRows(5);
        Txtconsola.setWrapStyleWord(true);
        jScrollPane2.setViewportView(Txtconsola);

        javax.swing.GroupLayout panelConsolaLayout = new javax.swing.GroupLayout(panelConsola);
        panelConsola.setLayout(panelConsolaLayout);
        panelConsolaLayout.setHorizontalGroup(
            panelConsolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsolaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 444, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelConsolaLayout.setVerticalGroup(
            panelConsolaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelConsolaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel2.setText("Consola");

        Archivo.setText("archivo");

        itemNuevo.setText("nuevo");
        itemNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNuevoActionPerformed(evt);
            }
        });
        Archivo.add(itemNuevo);

        itemAbrir.setText("abrir");
        itemAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAbrirActionPerformed(evt);
            }
        });
        Archivo.add(itemAbrir);

        itemGuardar.setText("guardar");
        itemGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGuardarActionPerformed(evt);
            }
        });
        Archivo.add(itemGuardar);

        itemGuardarComo.setText("Guardar como");
        itemGuardarComo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemGuardarComoActionPerformed(evt);
            }
        });
        Archivo.add(itemGuardarComo);

        itemSalir.setText("Salir");
        itemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSalirActionPerformed(evt);
            }
        });
        Archivo.add(itemSalir);

        menuBar.add(Archivo);

        MenuEjecutar.setText("Ejecutar");

        Ejecutar.setText("ejecutar ");
        Ejecutar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EjecutarActionPerformed(evt);
            }
        });
        MenuEjecutar.add(Ejecutar);

        menuBar.add(MenuEjecutar);

        menuReportes.setText("Reportes");

        itemTablaSimbolos.setText("Tabla de simbolos");
        itemTablaSimbolos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemTablaSimbolosActionPerformed(evt);
            }
        });
        menuReportes.add(itemTablaSimbolos);

        itemErrores.setText("Errores");
        itemErrores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemErroresActionPerformed(evt);
            }
        });
        menuReportes.add(itemErrores);

        menuASTAction.setText("AST");
        menuASTAction.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuASTActionActionPerformed(evt);
            }
        });
        menuReportes.add(menuASTAction);

        menuBar.add(menuReportes);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tabEditor, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panelConsola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(163, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tabEditor, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelConsola, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNuevoActionPerformed
        int numTabs = tabEditor.getTabCount() + 1;
        crearNuevaPestania("Sin título " + numTabs, "");
    }//GEN-LAST:event_itemNuevoActionPerformed

    private void itemAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAbrirActionPerformed
        javax.swing.JFileChooser chooser = new javax.swing.JFileChooser();
        chooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Archivos .ju", "ju"));
        int resultado = chooser.showOpenDialog(this);
        if (resultado == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File archivo = chooser.getSelectedFile();
            try {
                String contenido = new String(java.nio.file.Files.readAllBytes(archivo.toPath()), java.nio.charset.StandardCharsets.UTF_8);
                crearNuevaPestania(archivo.getName(), contenido);
                java.awt.Component comp = tabEditor.getSelectedComponent();
                archivosPorTab.put(comp, archivo);
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error al abrir archivo:\n" + e.getMessage());
            }
        }
    }//GEN-LAST:event_itemAbrirActionPerformed

    private void itemGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGuardarActionPerformed
        java.awt.Component comp = tabEditor.getSelectedComponent();
        java.io.File archivo = archivosPorTab.get(comp);

        if (archivo == null) {
            guardarComo(comp);
        } else {
            guardarEnArchivo(comp, archivo);
        }
    }//GEN-LAST:event_itemGuardarActionPerformed

    private void itemGuardarComoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemGuardarComoActionPerformed
         java.awt.Component comp = tabEditor.getSelectedComponent();
         guardarComo(comp);
    }//GEN-LAST:event_itemGuardarComoActionPerformed

    private void itemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_itemSalirActionPerformed

    private void EjecutarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EjecutarActionPerformed
    // ================= LIMPIAR CONSOLA =================
    limpiarConsola();
    Consola.escribirLinea(">> Consola conectada OK");

    String codigo = getTextoEditorActual();
    if (codigo == null || codigo.isBlank()) {
        Consola.escribirLinea("No hay código para analizar.");
        return;
    }

    // ================= LIMPIAR ERRORES =================
    olc1.proyecto.reportes.ReporteErrores.clear();

    // ================= CREAR ENTORNO GLOBAL =================
    this.envEjecucion = new olc1.proyecto.interprete.Entorno(null);

    try {
        // ================= LEXER / PARSER =================
        Lexer lexer = new Lexer(new java.io.StringReader(codigo));
        Parser parser = new Parser(lexer);

        Consola.escribirLinea("Iniciando análisis léxico y sintáctico...");
        Object resultado = parser.parse().value;
        Consola.escribirLinea("Análisis sintáctico finalizado.");

        // ================= EJECUCIÓN =================
        if (resultado instanceof java.util.List<?> lista) {

            Consola.escribirLinea("");
            Consola.escribirLinea("=== EJECUTANDO PROGRAMA ===");

            olc1.proyecto.ast.StartIns start = null;

            // 1) REGISTRAR TODO
            for (Object obj : lista) {
                if (obj instanceof olc1.proyecto.ast.Instruccion ins) {

                    if (ins instanceof olc1.proyecto.ast.StartIns s) {
                        start = s;
                        continue;
                    }

                    ins.ejecutar(this.envEjecucion);
                }
            }

            // 2) EJECUTAR START
            if (start != null) {
                start.ejecutar(this.envEjecucion);
            } else {
                Consola.escribirLinea("No se encontró START main();");
            }

            Consola.escribirLinea("=== FIN DE EJECUCIÓN ===");

            // ================= REPORTE AST =================
            StringBuilder astTexto = new StringBuilder();
            astTexto.append("AST - Lista de Instrucciones\n");
            astTexto.append("--------------------------------\n");

            for (Object obj : lista) {
                astTexto.append(obj.getClass().getSimpleName()).append("\n");
            }

            String gramaticaTexto =
                    "Gramática utilizada: Parser.cup\n" +
                    "Producciones cargadas correctamente.";

            String base = System.getProperty("user.dir");
            String rutaAST = base + java.io.File.separator + "ast.html";

            olc1.proyecto.reportes.ReporteAST.generarHTML(
                    rutaAST,
                    astTexto.toString(),
                    gramaticaTexto
            );

            this.ultimoReporteAST = new java.io.File(rutaAST);
            Consola.escribirLinea("Reporte AST: " + rutaAST);
        }

    } catch (Exception ex) {
        Consola.escribirLinea("Ocurrió una excepción durante el análisis:");
        Consola.escribirLinea(ex.getMessage());
    }

    // ================= REPORTES =================
    try {
        String base = System.getProperty("user.dir");

        String rutaTS = base + java.io.File.separator + "tabla_simbolos.html";
        olc1.proyecto.reportes.ReporteTablaSimbolos.generarHTML(rutaTS, envEjecucion);
        Consola.escribirLinea("Reporte TS: " + rutaTS);

        String rutaErr = base + java.io.File.separator + "errores.html";
        olc1.proyecto.reportes.ReporteErrores.generarHTML(rutaErr);
        Consola.escribirLinea("Reporte Errores: " + rutaErr);

        if (menuASTAction != null) {
            menuASTAction.setEnabled(true);
        }

    } catch (Exception ex) {
        Consola.escribirLinea("Error al generar reportes: " + ex.getMessage());
    }
    }//GEN-LAST:event_EjecutarActionPerformed

    private void itemTablaSimbolosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemTablaSimbolosActionPerformed
    try {
        if (this.envEjecucion == null) {
            Consola.escribirLinea("Primero ejecutá el programa (no hay entorno).");
            return;
        }

        String base = System.getProperty("user.dir");
        String rutaTS = base + java.io.File.separator + "tabla_simbolos.html";
        olc1.proyecto.reportes.ReporteTablaSimbolos.generarHTML(rutaTS, this.envEjecucion);

        java.io.File f = new java.io.File(rutaTS);
        java.awt.Desktop.getDesktop().browse(f.toURI());

    } catch (Exception ex) {
        Consola.escribirLinea("No se pudo abrir TS: " + ex.getMessage());
    }
    }//GEN-LAST:event_itemTablaSimbolosActionPerformed

    private void itemErroresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemErroresActionPerformed
      
    try {
        if (this.ultimoReporteErrores == null || !this.ultimoReporteErrores.exists()) {
            Consola.escribirLinea("Primero ejecutá el programa para generar el reporte de errores.");
            return;
        }
        java.awt.Desktop.getDesktop().browse(this.ultimoReporteErrores.toURI());
    } catch (Exception ex) {
        Consola.escribirLinea("No se pudo abrir Reporte de Errores: " + ex.getMessage());
    }


    }//GEN-LAST:event_itemErroresActionPerformed

    private void menuASTActionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuASTActionActionPerformed
   try {
        if (ultimoReporteAST != null && ultimoReporteAST.exists()) {
            java.awt.Desktop.getDesktop().browse(ultimoReporteAST.toURI());
        } else {
            Consola.escribirLinea("Reporte AST no generado todavía.");
        }
    } catch (Exception ex) {
        Consola.escribirLinea("No se pudo abrir el reporte AST: " + ex.getMessage());
    }
    }//GEN-LAST:event_menuASTActionActionPerformed

        private void guardarComo(java.awt.Component comp) {
        javax.swing.JFileChooser chooser = new javax.swing.JFileChooser();
        chooser.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Archivos .ju", "ju"));
        int resultado = chooser.showSaveDialog(this);
        if (resultado == javax.swing.JFileChooser.APPROVE_OPTION) {
            java.io.File archivo = chooser.getSelectedFile();
            // Asegurar extensión .ju
            if (!archivo.getName().toLowerCase().endsWith(".ju")) {
                archivo = new java.io.File(archivo.getAbsolutePath() + ".ju");
            }
            guardarEnArchivo(comp, archivo);
            archivosPorTab.put(comp, archivo);
            // Cambiar título de la pestaña
            int index = tabEditor.indexOfComponent(comp);
            if (index >= 0) {
                tabEditor.setTitleAt(index, archivo.getName());
            }
        }
    }

    private void guardarEnArchivo(java.awt.Component comp, java.io.File archivo) {
        javax.swing.JTextArea editor = null;
        if (comp instanceof javax.swing.JScrollPane) {
            javax.swing.JScrollPane scroll = (javax.swing.JScrollPane) comp;
            java.awt.Component view = scroll.getViewport().getView();
            if (view instanceof javax.swing.JTextArea) {
                editor = (javax.swing.JTextArea) view;
            }
        }
        if (editor != null) {
            try {
                String contenido = editor.getText();
                java.nio.file.Files.write(
                        archivo.toPath(),
                        contenido.getBytes(java.nio.charset.StandardCharsets.UTF_8)
                );
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Error al guardar archivo:\n" + e.getMessage());
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu Archivo;
    private javax.swing.JMenuItem Ejecutar;
    private javax.swing.JMenu MenuEjecutar;
    private javax.swing.JTextArea Txtconsola;
    private javax.swing.JMenuItem itemAbrir;
    private javax.swing.JMenuItem itemErrores;
    private javax.swing.JMenuItem itemGuardar;
    private javax.swing.JMenuItem itemGuardarComo;
    private javax.swing.JMenuItem itemNuevo;
    private javax.swing.JMenuItem itemSalir;
    private javax.swing.JMenuItem itemTablaSimbolos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenuItem menuASTAction;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuReportes;
    private javax.swing.JPanel panelConsola;
    private javax.swing.JTabbedPane tabEditor;
    // End of variables declaration//GEN-END:variables
}
