
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package olc1.proyecto.analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int CHAR_LIT = 27;
  public static final int POT = 34;
  public static final int POR = 31;
  public static final int CHAR = 6;
  public static final int FIND = 62;
  public static final int REMOVE = 61;
  public static final int XOR = 43;
  public static final int CASE = 22;
  public static final int DOUBLE = 4;
  public static final int CONTINUE = 17;
  public static final int INT = 3;
  public static final int COR_CIERRA = 52;
  public static final int FOR = 15;
  public static final int PAR_ABRE = 47;
  public static final int NOT = 44;
  public static final int AND = 41;
  public static final int APPEND = 60;
  public static final int IGUAL = 35;
  public static final int COR_ABRE = 51;
  public static final int OR = 42;
  public static final int BOOL = 5;
  public static final int INC = 45;
  public static final int DIV = 32;
  public static final int DOUBLE_LIT = 25;
  public static final int IF = 11;
  public static final int ID = 28;
  public static final int EOF = 0;
  public static final int RETURN = 18;
  public static final int TRUE = 9;
  public static final int NEW = 57;
  public static final int error = 1;
  public static final int COMA = 55;
  public static final int DIF = 36;
  public static final int MENOS = 30;
  public static final int MOD = 33;
  public static final int START = 20;
  public static final int BREAK = 16;
  public static final int VOID = 8;
  public static final int LLAVE_ABRE = 49;
  public static final int MENIG = 38;
  public static final int SWITCH = 21;
  public static final int ELSE = 12;
  public static final int PUNTO = 59;
  public static final int MAYIG = 40;
  public static final int MEN = 37;
  public static final int WHILE = 13;
  public static final int LIST = 58;
  public static final int DEFAULT = 23;
  public static final int ASIGN = 56;
  public static final int DOSP = 54;
  public static final int PTCOMA = 53;
  public static final int STRING = 7;
  public static final int LLAVE_CIERRA = 50;
  public static final int DEC = 46;
  public static final int FALSE = 10;
  public static final int PAR_CIERRA = 48;
  public static final int MAY = 39;
  public static final int STRING_LIT = 26;
  public static final int INT_LIT = 24;
  public static final int VAR = 2;
  public static final int PRINT = 19;
  public static final int DO = 14;
  public static final int MAS = 29;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "VAR",
  "INT",
  "DOUBLE",
  "BOOL",
  "CHAR",
  "STRING",
  "VOID",
  "TRUE",
  "FALSE",
  "IF",
  "ELSE",
  "WHILE",
  "DO",
  "FOR",
  "BREAK",
  "CONTINUE",
  "RETURN",
  "PRINT",
  "START",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "INT_LIT",
  "DOUBLE_LIT",
  "STRING_LIT",
  "CHAR_LIT",
  "ID",
  "MAS",
  "MENOS",
  "POR",
  "DIV",
  "MOD",
  "POT",
  "IGUAL",
  "DIF",
  "MEN",
  "MENIG",
  "MAY",
  "MAYIG",
  "AND",
  "OR",
  "XOR",
  "NOT",
  "INC",
  "DEC",
  "PAR_ABRE",
  "PAR_CIERRA",
  "LLAVE_ABRE",
  "LLAVE_CIERRA",
  "COR_ABRE",
  "COR_CIERRA",
  "PTCOMA",
  "DOSP",
  "COMA",
  "ASIGN",
  "NEW",
  "LIST",
  "PUNTO",
  "APPEND",
  "REMOVE",
  "FIND"
  };
}

